# Generated by Django 3.0.8 on 2020-07-15 07:25

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntingspot',
            name='adress',
            field=djgeojson.fields.PointField(default=1),
            preserve_default=False,
        ),
    ]
