# Generated by Django 3.0.8 on 2020-07-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_huntingspot_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huntingspot',
            old_name='adress',
            new_name='addresss',
        ),
    ]
