# Generated by Django 3.0.8 on 2020-07-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200715_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huntingspot',
            old_name='address',
            new_name='geom2',
        ),
    ]
