# Generated by Django 3.0.8 on 2020-07-15 07:43

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200715_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntingspot',
            name='geom',
            field=djgeojson.fields.PolygonField(blank=True),
        ),
        migrations.AlterField(
            model_name='huntingspot',
            name='geom2',
            field=djgeojson.fields.PointField(blank=True),
        ),
    ]
