# Generated by Django 3.0.8 on 2020-07-15 08:24

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20200715_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntingspot',
            name='geom1',
            field=djgeojson.fields.PolygonField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='huntingspot',
            name='geom',
            field=djgeojson.fields.GeometryCollectionField(),
        ),
    ]
